version: "3"
services:
  train:
    image: train:v1
    ports:
      - "81:80"
    deploy:
      replicas: 3

  movie:
    image: movie:v1
    ports:
      - "82:80"
    deploy:
      replicas: 3      

  dth:
    image: dth:v1
    ports:
      - "83:80"
    deploy:
      replicas: 3  

  recharge:
    image: recharge:v1
    ports:
      - "84:80"
    deploy:
      replicas: 3
